<template>
  <div class="section">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus animi asperiores commodi deserunt error esse eveniet ex explicabo harum id illo ipsa iste minus molestias natus nobis nulla praesentium quae qui quidem quis quos repellat soluta, tempora vel voluptate voluptatibus! Adipisci blanditiis consequatur cum earum eius minima necessitatibus sed sint voluptate. Accusantium adipisci alias architecto consequuntur cumque delectus dicta doloremque doloribus earum eligendi enim error esse et eum in incidunt iste iure labore magni mollitia, optio perspiciatis porro quas quibusdam quidem repellendus unde voluptate? Cum cumque dolores doloribus expedita hic id illo, impedit inventore laboriosam laudantium qui quisquam, quos repudiandae?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus animi asperiores commodi deserunt error esse eveniet ex explicabo harum id illo ipsa iste minus molestias natus nobis nulla praesentium quae qui quidem quis quos repellat soluta, tempora vel voluptate voluptatibus! Adipisci blanditiis consequatur cum earum eius minima necessitatibus sed sint voluptate. Accusantium adipisci alias architecto consequuntur cumque delectus dicta doloremque doloribus earum eligendi enim error esse et eum in incidunt iste iure labore magni mollitia, optio perspiciatis porro quas quibusdam quidem repellendus unde voluptate? Cum cumque dolores doloribus expedita hic id illo, impedit inventore laboriosam laudantium qui quisquam, quos repudiandae?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus animi asperiores commodi deserunt error esse eveniet ex explicabo harum id illo ipsa iste minus molestias natus nobis nulla praesentium quae qui quidem quis quos repellat soluta, tempora vel voluptate voluptatibus! Adipisci blanditiis consequatur cum earum eius minima necessitatibus sed sint voluptate. Accusantium adipisci alias architecto consequuntur cumque delectus dicta doloremque doloribus earum eligendi enim error esse et eum in incidunt iste iure labore magni mollitia, optio perspiciatis porro quas quibusdam quidem repellendus unde voluptate? Cum cumque dolores doloribus expedita hic id illo, impedit inventore laboriosam laudantium qui quisquam, quos repudiandae?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus animi asperiores commodi deserunt error esse eveniet ex explicabo harum id illo ipsa iste minus molestias natus nobis nulla praesentium quae qui quidem quis quos repellat soluta, tempora vel voluptate voluptatibus! Adipisci blanditiis consequatur cum earum eius minima necessitatibus sed sint voluptate. Accusantium adipisci alias architecto consequuntur cumque delectus dicta doloremque doloribus earum eligendi enim error esse et eum in incidunt iste iure labore magni mollitia, optio perspiciatis porro quas quibusdam quidem repellendus unde voluptate? Cum cumque dolores doloribus expedita hic id illo, impedit inventore laboriosam laudantium qui quisquam, quos repudiandae?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus animi asperiores commodi deserunt error esse eveniet ex explicabo harum id illo ipsa iste minus molestias natus nobis nulla praesentium quae qui quidem quis quos repellat soluta, tempora vel voluptate voluptatibus! Adipisci blanditiis consequatur cum earum eius minima necessitatibus sed sint voluptate. Accusantium adipisci alias architecto consequuntur cumque delectus dicta doloremque doloribus earum eligendi enim error esse et eum in incidunt iste iure labore magni mollitia, optio perspiciatis porro quas quibusdam quidem repellendus unde voluptate? Cum cumque dolores doloribus expedita hic id illo, impedit inventore laboriosam laudantium qui quisquam, quos repudiandae?</p>
  </div>
</template>

<script>
export default {
  name: "PrivacyPolicy"
}
</script>
